services:
  worker:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/hatchet/epengine:latest
    build:
      context: .
      dockerfile: epengine/worker/Dockerfile
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 1
  api:
    build:
      context: .
      dockerfile: epengine/api/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:80"
