services:
  worker:
    build:
      context: .
      dockerfile: epengine/worker/Dockerfile
    env_file:
      - .env
  api:
    build:
      context: .
      dockerfile: epengine/api/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:80"
